rust-lang/libz-sys

Cargo.toml

This library expects `get_compiler()` to return a `Tool` rather than a tuple, which is correct starting in 0.3.17.

Update gcc requirement.

---

src/lib.rs

Adhere to the libc/bindgen standard by implementing Clone and Copy on all repr(C) structs.

Implement Clone,Copy

---

Cargo.toml
appveyor.yml
build.rs

Use zlib from vcpkg. This one is not behind a feature flag but the vcpkg build helper has similar opt-out mechanisms to pkg-config.
This would be required in order to merge https://github.com/alexcrichton/curl-rust/pull/166.

use static or dynamic build of zlib from vcpkg

---

build.rs

```
NMAKE : fatal error U1065: invalid option '-'
Stop.
Command exited with code 101
```

nmake chokes on MAKEFLAGS for jobserver (unmergeable repro)

---

build.rs

Note: This applies to all other BSDs as well. Hard coding it in this way
should be generally avoided if possible.

Use gmake on DragonFly as well

---

appveyor.yml

This stops recent vcpkg hanging in appveyor.

suppress interactive vcpkg prompt in appveyor

---

README.md

The README says "...for inclusion in Serde..." but I guess it meant to say "...for inclusion in libz-sys...".

Fix contribution notice

---

build.rs

Avoid the same `-L/usr/lib` problem as on macOS.

Don't run pkg-config on FreeBSD and DragonFlyBSD

---

systest/Cargo.toml

Updates the `systest` crate's dependencies.
`libc` was updated from 0.1 to 0.2, and `ctest` was set to version 0.1

Update `systest` dependencies

---

src/lib.rs

`zlib` can be built to use the `__stdcall` calling convention on Windows, but it prefers to use `__cdecl` wherever possible.
From the `zlib` readme for Windows:
> There is also an **official** DLL build of zlib, named zlib1.dll. This one
> is exporting the functions using the CDECL convention. See the file
> win32\DLL_FAQ.txt found in this zlib distribution.
This issue was not found before because:
- on 64-bit Windows and all other platforms, `extern "system"` is the same as `extern`.
- 32-bit MSVC doesn't even check for calling conventions.
- 32-bit GCC did produce errors, but they were unclear (unlike the Rust compiler, it does not say which part of the function type is wrong).
Fixes `i686-pc-windows-gnu` builds.

Use C calling convention everywhere

---

build.rs

No more dealing with tons of platforms and bending over backwards, let's just
compile C code.
More info in alexcrichton/curl-rust#225

Use `cc` crate to build zlib

---

build.rs

It seems that snprintf and family are feature-gated behind either
`_POSIX_C_SOURCE=200112L`, `_C99_SOURCE`, or `__cplusplus` within the iOS 12
SDK stdio.h decls. This change gives successful cross-compilation
builds (from host `x86_64-apple-darwin`) for:
* `aarch64-apple-ios`
* `armv7-apple-ios`
* `armv7s-apple-ios`
* `x86_64-apple-ios`
* `i386-apple-ios`
Fixes #44

Define _C99_SOURCE for iOS targets

---

Cargo.toml
build.rs
systest/Cargo.toml

There is a way to build statically linked crate right now, however, it requires the environment variable `LIBZ_SYS_STATIC=1`. This can be suboptimal when as it makes the build to not be self-contained.
This PR adds feature `static` that triggers the same processing as the env var.

Add 'static' feature to build a statically linked crate

---

Cargo.toml
build.rs
src/lib.rs

Adds a `libc` feature which is enabled by default, but opting out from it allows to build zlib with Z_SOLO mode.
This mode removes dependency on any external libraries including libc at the cost of eliminating some high-level functions like gz*, compress* and uncompress, and requiring embedder to provide memory allocation routines to deflate and inflate.
This is useful for targets without libc support such as embedded targets or wasm32-unknown-unknown, as well as for embedding in crates that provide own allocation anyway.
An an example of the latter, when using this mode from a local branch of flate2, the output artifact of `cargo build --release --example compress_file --features zlib` in flate2 goes down by 7KB, even though all the functionality is still available as before.
Note: the …

Allow building zlib without libc

---

build.rs

Adding system-wide library directories to the linker search path causes these
directories to be searched before other paths added by later crates. If a
library is present in the system-wide directory and a later crate wants to
specifically link against a different version of that library in another path,
the linker will choose the library from the first search directory it
finds. If the linker doesn't find a library in any of the specified search
directories, it falls back on system-wide paths, so we don't need to print the
path we found zlib in if it is in one of those system paths.
This resolves issue #49.

Don't let pkg-config add system lib dirs to the search path

---

.gitmodules
.travis.yml
Cargo.toml
README.md
appveyor.yml
build.rs
systest/Cargo.toml
systest/build.rs

Add support for building libz-sys using zlib-ng in zlib-compat mode.
By default, `libz-sys` still uses stock zlib, primarily because doing so allows the use of a shared system zlib library if available.
Any application or library designed for zlib should work with zlib-ng in zlib-compat mode, as long as it doesn't make assumptions about the exact size or output of the deflated data (e.g. "compressing this data produces exactly this many bytes"), and as long as you don't also dynamically pull in a copy of stock zlib (which will produce conflicting symbols). Nonetheless, for maximum compatibility, every library crate in a build must opt into allowing zlib-ng; if any library crate in your dependency graph wants stock zlib, `libz-sys` will use stock zlib.
Library crates depending on …

Add support for zlib-ng

---

Cargo.toml
systest/Cargo.toml
systest/build.rs

I saw Josh opened this issue: https://github.com/gnzlbg/ctest/issues/99
That's because we use ctest v0.1 here, it's outdated a bit. We could fix this issue by updating it to v0.2 but it will emit uninitialized errors, like this: https://github.com/JohnTitor/libz-sys/runs/1014401885
So, if you want to get rid of the warnings, I'd recommend using ctest2, which is a fork of ctest and has some fixes: https://github.com/JohnTitor/ctest2
I created this to use on the libc crate, but I hope this helps here as well :)

Use `ctest2` instead of the original to fix warnings

---

build.rs

I've noticed that this crate already supports `wasm32-unknown-unknown`. This PR also makes the crate compile for `wasm32-wasi`.

Make it compile for wasm32-wasi

---

build.rs

When rustc and cargo are built for Haiku, they are cross-compiled from Linux.
The current logic of the build script decides to build from source when
cross-compiling. On Haiku, this is unnecessary. We can safely assume that
libz.so is on the target system. Therefore, like with Android, we can always
link to it.

Haiku: always link to the system libz.so.

---

build.rs

I use Void Linux with `musl` as system libc (I don't use glibc at all). I'm trying to make a package for [wezterm](https://github.com/wez/wezterm). `wezterm` depends on `libz-sys`, and it fails to build because it tries to build `zlib` from source and it obviously doesn't find them.
So I suggest removing this hardcoded vendoring for musl, because your assumptions about musl being used for embedded statically build stuff is wrong. There are at least 3 distros from top of my mind which use musl: Void Linux, Alpine Linux, Adélie Linux.
Another option would be downloading `zlib` or `zlib-ng` sources tarball, unpacking it into the right location before starting to build `wezterm`. But it seems hacky and harder than removing single line from `libz-sys`'s `build.rs`.
See also: …

Disable forced zlib vendoring on musl

---

build.rs

Common cmake script uses builtin `FindZLIB` module to find where zlib is
installed. The cmake crate allows `register_dep` to hint cmake to search
the right place. libz-sys puts the library under build directory, which
is however not the place where cmake is going to search. So this PR
corrects the behavior by moving the built library to lib directory.
Another option is to set the root directory to build instead, but the
layout may not look good.
It has been an issue for downstream projects like tikv/rust-rocksdb#303
and tikv/grpc-rs#419.

make static build compatible with cmake

---

build.rs

Docs: https://github.com/zlib-ng/zlib-ng/tree/develop/arch/s390

Add support for hardware compression on s390x for zlib-ng

---

build.rs

Without this warning, it only shows include error for `zlib.h`.
closes #70

Show pkg-config error as warning

---

build.rs

Current zlib-ng uses "zlibstatic" for the static library on MSVC Windows
only, and uses just "z" for non-MSVC Windows targets.

build.rs: Fix library name on Windows, with and without MSVC

---

build.rs

Current zlib-ng defines _POSIX_C_SOURCE, which causes macOS sys/types.h
to not define types like u_char and u_int, which leads to compilation
errors when including other headers that use those types.
Define _DARWIN_C_SOURCE to work around this, which causes macOS
sys/types.h to define these types again.

Fix build on macOS

---

build.rs

I'm pretty sure this is the correct way to set this; it seems to pass CI anyway.  Not really an area I'm an expert in...  If there's a better way to do this lmk.

Fix zlib-ng win32 builds

---

build.rs

zlib-ng commit a39e323a4db80a57feecf2ae212c08070234050c ("Added memory alignment compensation functions for users who may be using custom allocators that don't align on the same boundary zlib-ng expects.") fixes the segfault.
Update zlib-ng to the latest version that passes flate2's testsuite.
Also, prevent the zlib-ng build process from touching the network, by not building the zlib-ng testsuite (which we don't invoke). This will improve build time as well.

Update zlib-ng to fix segfault due to unaligned access

---

src/lib.rs

`libc` doesn't have `off_t` for WebAssembly without WASI, so it falls
back to `long`.  Do the same in this crate to fix the build error when
trying to statically build libz for WebAssembly.
Rough code from `zconf.h` declaring `z_off_t`:
```c++
#ifndef Z_SOLO
// [...]
#endif
// [...]
#ifndef z_off_t
#endif
```
Fixes #95.

Fix static wasm build without wasi

---

Cargo-zng.toml
Cargo.toml
README-zng.md
README.md
build.rs
build_zng.rs
cargo-zng
ci/test.bash
src/lib.rs
systest/Cargo-zng.toml
systest/Cargo.toml
systest/build.rs
systest/src/main.rs

libz-ng-sys uses the zlib-ng native API, rather than the zlib-compat
API. It exports the same Rust API (modulo the slight differences in
types), without the `zng_` prefixes, to make it easy to write Rust
software that works with both.
Add a separate Cargo.toml and README for libz-ng-sys.
Move the `build_zlib_ng` function from `build.rs` to `build_zng.rs`, and
use that as the build script for libz-ng-sys.
Add a cargo-zng script that creates the libz-ng-sys crate in a temporary
directory and runs cargo on it, to make it easy to run tests with:
```
./cargo-zng test
./cargo-zng run --manifest-path systest/Cargo.toml
```
Test libz-ng-sys in CI.

Add a libz-ng-sys crate, using the same sources with minimal duplication

---

Cargo-zng.toml
Cargo.toml
build_zng.rs

Now that upstream has commit 84f116a3d782b39047b666bc6804e2c0c2138e6d,
we are no longer blocked from upgrading.
We want commit 9be98893aaf69892811d617122e28ea2dd8e17ba, to avoid
conflicts between zlib and zlib-ng when building in native mode (for
libz-ng-sys).
Also, thanks to commit d41f8ead569ee805b323b45fca30430cefe91cfd, we can
eliminate the code explicitly setting `_DARWIN_C_SOURCE`.

Upgrade to current zlib-ng to get fix for internal symbol collisions

---

.github/dependabot.yml
.github/workflows/ci.yml

- Setup Dependabot for GHA
- Upgrade some external actions
- Pin hash instead of tag to reduce security risk
- it's less readable but Dependabot will take care of upgrades by tag in comments

Refine GHA

---

build.rs

Calling `pkg-config zlib` does not print `-L /usr/lib` for any zlib
package that I'm aware of on macOS (not even the one provided by Apple).
Moreover, the comment about a `-L /usr/lib` flag wreaking havoc on
attempting to link with OpenSSL in `/usr/local/lib` should no longer be
true. Presumbly, this was the case when Apple shipped its own
`libcrypto` and `libssl` in `/usr/lib`, but those days are long gone.

Run `pkg-config` on macOS.

---

Cargo-zng.toml
Cargo.toml

Note that we have to release `libz-ng-sys` too by `cargo-zng publish`.
r? @Mark-Simulacrum

Prepare 1.1.9 release

---

build.rs

The `zlib_installed` function does not use the correct compiler flags when checking if there already is a libz library pre-build.
This causes libz-sys to build the internal libz version, which might be different from the pre-build libz version, and might cause issues with other libraries which also used the pre-build libz wether or not it's static or shared.
I came across this when using my custom toolchain build images to build static musl binaries. And this crate seemed to build the built-in version anyways. Which is an other issue, not addressed in this PR.

Fix `zlib_installed` not using the correct flags

---

cargo-zng

The `--verbatim-files-from` options doesn't seem to be needed as they are 'plain' enough.

`cargo-zng` now works on MacOS

---

ci/test.bash
src/lib.rs
systest/build.rs

zlib-ng 2.1.2 is the first stable release of the 2.1.x branch.
Most important optimizations and Enhancements:
* Decompression is a lot faster (56% faster measured on AVX2-capable x86-64)
* Compresson is improved for Level 9, at the cost of a little performance.
* Compression is improved for Level 3, by switching from deflate_fast to deflate_medium.
[Full changelog](https://github.com/zlib-ng/zlib-ng/releases/tag/2.1.2)

Update zlib-ng to 2.1.3

---

Cargo.toml
build.rs

`vcpkg-rs` doesn't support `-pc-windows-gnu` (mingw) _yet_, but its integration tests will try to build `libz-sys`, which currently prevents using `vcpkg` for non-`msvc` targets.
This change should have no effect for `libz-sys` right now, but unblocks that work.
This also switches from `vcpkg::lib_names`/`probe` to `vcpkg::find_package`, which reliably gets the library names. Previously, this had hard coded assumptions using MSVC-style library naming (no `lib` prefix).

Allow using vcpkg for all Windows targets, and use find_package

---

build.rs

The root cause of the pkg-config failure on MSVC seems to be that pkg-config-rs is appending .lib, while it shouldn't because rustc already does that on Windows.
@sdroege is fixing this issue in https://github.com/alexcrichton/pkg-config-rs/pull/72.

Run pkg-config on MSVC

---

build_zng.rs

On same platform, library file is compiled into `lib64` directory. Rust compiler expects that library will be in `lib` directory. This fixes this by searing library both in `lib` and `lib64` directory.

Fix build on x86_64

---

Cargo-zng.toml
Cargo.toml

libz-sys should now build on non-debian linuxes again which need a different
search path.

bump patch level for hotfix release

---

build.rs

Added version, that is parsed from zlib.h and `includedir` and `libdir`

Write more variables into zlib.pc

---

build.rs

Really try dylib when compiling for Apple platforms

---

README-zng.md

Noticed a minor typo in this README.

Correct README typo for libz-ng-sys

---

build.rs

Downstream build scripts use `DEP_Z_INCLUDE` to configure the builds of other native libraries (for example in [libgit2-sys](https://github.com/rust-lang/git2-rs/blob/master/libgit2-sys/build.rs#L226)). Previously, if libz was found via pkg-config and didn't have a system-default include directory those builds would fail.

Also emit DEP_Z_INCLUDE when using pkg-config

---

.github/workflows/ci.yml
Cargo.toml
zng/cc.rs

Add missing package files

---

zng/cc.rs

* Fix armv7-unknown-linux-musleabi and arm-unknown-linux-musleabi by only passing in ARM_NEON if that target is enabled.
* This was only tested without neon, and *not* tested *with* neon support
To enable NEON in the future, I think the following will need to be addressed with adding compiler options:
```
cargo:warning=                 from src/zlib-ng/arch/arm/slide_hash_neon.c:12:
cargo:warning=/usr/local/lib/gcc/arm-linux-musleabi/9.2.0/include/arm_neon.h:31:2: error: #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
cargo:warning=   31 | #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
```

cc: Only enable ARM_NEON when in target_feature

---

build.rs

Currently when compiling for android/haiku target we check pkg-config
for zlib then fallback to using shipped zlib,
this can cause problems as pkg-config sometimes returns host's zlib.
This patch makes it to always use shipped zlib instead of pkg-config one (moves `target.contains("android")` check before pkg-config check).

Do not check pkg-config when cross-compiling for android

---

.github/dependabot.yml

This project uses the `upload-artifact` and `download-artifact` actions which, when updated with breaking changes, must be advanced together. But currently Dependabot attempts to update them separately. Each of the pull requests #184 and #186 were created separately, so they both fail for the checks that use `cross` (since the `cross` binary is cached as an artifact). If they were both merged in the hope that, together, they would work, then that would run the risk of missing some other problem, and it would also create a situation where, after one has been merged and the other has not, CI would be broken.
This modifies `dependabot.yml` so that Dependabot version updates are grouped. This should always solve that kind of problem, and do so without sacrificing automation. I have confirmed …

Group Dependabot version updates

---

Cargo.toml

fixes #204 
the typo meant that some C files were not included in the build, which caused the published version of this crate to fail for s390x targets
Also bumps the version because having this fixed on crates.io would be nice.
```
> ls src/zlib-ng/arch
arm  generic  power  riscv  s390  x86
```

fix typo in the s390/s390x inclusion

---

.github/workflows/ci.yml
Cargo-zng.toml
Cargo.toml

Help discover bugs in version requ
irements

Add minimal-versions CI

---

build.rs

The warning wasn't actually printed by Cargo

Fix cargo:warning syntax in build.rs

---

cargo-zng

Fixes #212
`tr`-ing the `\` characters to `/` in the output of `cargo package -l` makes the `tar` pipeline work and allows the build to succeed on Windows, presumably since files needed by `cmake` are now available:
```text
ek@Glub MINGW64 ~/source/repos/libz-sys (dirsep)
$ ./cargo-zng build
Updating crates.io index
Locking 40 packages to latest compatible versions
Adding bitflags v1.3.2 (latest: v2.6.0)
Adding cfg-if v0.1.10 (latest: v1.0.0)
Adding dirs v2.0.2 (latest: v5.0.1)
Adding dirs-sys v0.3.7 (latest: v0.4.1)
Adding term v0.6.1 (latest: v1.0.0)
Adding wasi v0.11.0+wasi-snapshot-preview1 (latest: v0.13.2+wasi-0.2.1)
Compiling shlex v1.3.0
Compiling libc v0.2.158
Compiling cc v1.1.16
Compiling cmake v0.1.51
Compiling libz-ng-sys v1.1.16 …
```

Treat `\` in `cargo package -l` output as `/`

---

cargo-zng

The `cargo-zng` script contained:
```bash
trap 'rm -rf "$tempdir"' 0 INT
tempdir="$(mktemp -d)"
```
That releases a resource that may occasionally not have been acquired.
In the rare case that the script would be interrupted before `$tempdir` was set, this would attempt to read the previous value of `$tempdir`. But if the calling environment had an environment variable of this name, then its value would have been inherited as the initial `$tempdir` in the script, and wrongly deleted.
The change made here puts the commands in the other order, so we only arrange for the deletion of `$tempdir` once the directory we want to delete exists and `$tempdir` will definitely expand to its name and not that of another directory.
In a sense, this trades one race condition for another, in that now the …

Fix race condition scheduling `$tempdir` deletion

---

cargo-zng

Fixes #214
In the `cargo-zng` script, this has the `grep -v` command that filters out `Cargo.toml.orig` also filiter out `.cargo_vcs_info.json`.
It also refactors the command to use fixed string (`-F`) and match whole lines (`-x`), to eliminate the `^` and `$` anchors and `\` escapes from the pattern(s).
This is working for `./cargo-zng` and `./cargo-zng build` on Ubuntu 24.04 LTS, macOS 14.6, and Windows 10 in Git Bash.

Also `grep -v` out `.cargo_vcs_info.json` in `cargo-zng`

---

build.rs

The OpenHarmony SDK / sysroot contains libz.so and similar to android we can assume that libz will always be available, 
since the [OpenHarmony zlib documentation](https://docs.openharmony.cn/pages/v5.0/en/application-dev/reference/native-lib/zlib.md) exists and explicitly mentions linking against `libz.so`.
OpenHarmony is supported as a tier 2 target in rustc as [*-linux-ohos](https://doc.rust-lang.org/rustc/platform-support/openharmony.html)

ohos: Link shared lib on OpenHarmony

---

zng/cc.rs

Workaround for #230.
Don't really have time to look at this more in depth, so this just disables neon intrinsics for apple targets leaving the rest of them untouched. There's probably just a missing flag or something, but someone who actually has the will to compile for aarch64-apple-darwin can maybe figure that out.

Disable neon for apple targets

---

Cargo.toml

Updates to the latest zlib-ng release https://github.com/zlib-ng/zlib-ng/releases/tag/2.2.3, released last week.

bump `zlib-ng` to version `2.2.3`

---

Cargo-zng.toml

It looks like the `zng` and "vanilla" version release in tandem? or should the version bump of `Cargo.toml` be reverted?

bump `zng` to 1.1.21

---

zng/cmake.rs

The linker on macOS warns on unused search paths, and concretely, when compiling `zlib-ng` via this crate, it warns with:
```
ld: search path 'target/debug/build/libz-sys-3eb8b95c9c44bf93/out/lib64' not found
```
This warning has previously been hidden away, but `rustc` wants to surface them by default [at some point](https://github.com/rust-lang/rust/issues/136096).
So let's avoid the warning by setting `CMAKE_INSTALL_LIBDIR` explicitly, and then only passing a single search path to the linker.
Can be tested on macOS with:
```console
$ RUSTFLAGS="-Wlinker-messages" cargo +nightly test --no-default-features --features zlib-ng
```

Fix unnecessary search path warning on macOS

---

Cargo-zng.toml
Cargo.toml

turns out zlib-ng had another release, with mostly bug fixes https://github.com/zlib-ng/zlib-ng/releases/tag/2.2.4.
Not urgent at all but we may as well stay up to date.

bump `zlib-ng` to version `2.2.4`

---

build.rs

This constraint is no longer necessary, due to improvements since it's original introduction in Feb 2016.
The zlib library will be linked dynamically (provided no explicit opt-in to static link) or fallback to building from source.
---
More details with discussion/history is covered here: https://github.com/rust-lang/libz-sys/pull/206#issuecomment-3026759631
**Notably:**
- A project should not link zlib both dynamically (_via another crate linking system deps that bring in zlib_) and statically (_vendored via `libz-sys`_): https://github.com/rust-lang/libz-sys/issues/201
- Building a target as a native arch or cross-compiled arch should not cause linking between dynamic vs static to occur when zlib is discoverable to link dynamically.
This PR ensures building for the target is consistent …

fix: Remove forcing static builds when cross-compiling
